# Generated by Django 4.1.7 on 2023-03-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('attributes', models.TextField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
