# Generated by Django 4.1.7 on 2023-03-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='date',
            new_name='purchased',
        ),
    ]
