# Generated by Django 4.1.7 on 2023-03-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_date_nft_purchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Feeding Date')),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nft')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
